import type { GameCard } from "@/types/game";

export const BUILDING_CARDS: GameCard[] = [
  {
    id: "starting-desk",
    name: "Bureau de départ",
    type: "building",
    rarity: "common",
    level: 1,
    maxLevel: 3,
    cost: { budget: 0 },
    production: { ideas: 1 },
    description: "Le point de départ de toute grande aventure.",
    tags: ["office", "starter"],
    capacity: 2,
    connectionsMax: 3,
    imageEmoji: "🖥️",
  },
  {
    id: "open-space",
    name: "Open Space",
    type: "building",
    rarity: "common",
    level: 1,
    maxLevel: 3,
    cost: { budget: 30 },
    production: { ideas: 3 },
    description: "Là où les idées circulent, parfois trop fort.",
    tags: ["office", "productivity", "social"],
    capacity: 4,
    connectionsMax: 4,
    imageEmoji: "🏢",
  },
  {
    id: "project-room",
    name: "Salle projet",
    type: "building",
    rarity: "uncommon",
    level: 1,
    maxLevel: 3,
    cost: { budget: 40, ideas: 5 },
    production: { ideas: 2 },
    description: "Une salle pour transformer les idées en vrais plans.",
    tags: ["project", "productivity"],
    capacity: 3,
    connectionsMax: 4,
    imageEmoji: "📋",
  },
  {
    id: "coffee-corner",
    name: "Coin café",
    type: "building",
    rarity: "common",
    level: 1,
    maxLevel: 3,
    cost: { budget: 25 },
    production: { energy: 2, happiness: 1 },
    description: "Le vrai moteur de l’entreprise.",
    tags: ["comfort", "energy"],
    capacity: 2,
    connectionsMax: 3,
    imageEmoji: "☕",
  },
  {
    id: "meeting-room",
    name: "Salle réunion",
    type: "building",
    rarity: "uncommon",
    level: 1,
    maxLevel: 3,
    cost: { budget: 45 },
    production: { ideas: 2, stress: 1 },
    description: "Peut créer des idées ou vider les âmes. Ça dépend.",
    tags: ["meeting", "productivity", "stress"],
    capacity: 6,
    connectionsMax: 4,
    imageEmoji: "🪑",
  },
  {
    id: "relax-corner",
    name: "Coin détente",
    type: "building",
    rarity: "uncommon",
    level: 1,
    maxLevel: 3,
    cost: { budget: 35 },
    production: { happiness: 3, stress: -2 },
    description: "Un canapé, une plante, et soudain tout va mieux.",
    tags: ["comfort", "happiness"],
    capacity: 3,
    connectionsMax: 3,
    imageEmoji: "🛋️",
  },
  {
    id: "creative-studio",
    name: "Studio créatif",
    type: "building",
    rarity: "rare",
    level: 1,
    maxLevel: 3,
    cost: { budget: 70, ideas: 15 },
    production: { ideas: 4 },
    description: "Les murs sont couverts de post-its et de grandes ambitions.",
    tags: ["creative", "ideas"],
    capacity: 4,
    connectionsMax: 4,
    imageEmoji: "🎨",
  },
  {
    id: "it-support-room",
    name: "Support IT",
    type: "building",
    rarity: "rare",
    level: 1,
    maxLevel: 3,
    cost: { budget: 60, energy: 5 },
    production: { energy: 1 },
    description: "Réduit les problèmes techniques et sauve les démos.",
    tags: ["technical", "support"],
    capacity: 2,
    connectionsMax: 3,
    imageEmoji: "🛠️",
  },
  {
    id: "prototype-lab",
    name: "Laboratoire prototype",
    type: "building",
    rarity: "rare",
    level: 1,
    maxLevel: 3,
    cost: { budget: 90, ideas: 20 },
    production: { reputation: 1, stress: 1 },
    description: "Fabrique des trucs brillants. Parfois ils explosent.",
    tags: ["prototype", "technical", "project"],
    capacity: 3,
    connectionsMax: 4,
    imageEmoji: "🤖",
  },
];

export const PERSON_CARDS: GameCard[] = [
  {
    id: "motivated-intern",
    name: "Stagiaire motivé",
    type: "person",
    rarity: "common",
    level: 1,
    maxLevel: 3,
    cost: { budget: 10 },
    production: { ideas: 1 },
    description: "Il ne sait pas encore tout faire, mais il veut tout essayer.",
    tags: ["junior", "ideas"],
    connectionsMax: 2,
    imageEmoji: "🧢",
  },
  {
    id: "tired-dev",
    name: "Développeur fatigué",
    type: "person",
    rarity: "uncommon",
    level: 1,
    maxLevel: 3,
    cost: { budget: 25 },
    production: { ideas: 2, energy: -1 },
    description: "Produit beaucoup, dort peu, demande du café.",
    tags: ["technical", "ideas", "fatigue"],
    connectionsMax: 3,
    imageEmoji: "💻",
  },
  {
    id: "inspiring-manager",
    name: "Manager inspirant",
    type: "person",
    rarity: "uncommon",
    level: 1,
    maxLevel: 3,
    cost: { budget: 35 },
    production: { happiness: 2, ideas: 1 },
    description: "Transforme une réunion normale en moment presque utile.",
    tags: ["management", "happiness"],
    connectionsMax: 3,
    imageEmoji: "🙋",
  },
  {
    id: "overloaded-designer",
    name: "Designer débordé",
    type: "person",
    rarity: "uncommon",
    level: 1,
    maxLevel: 3,
    cost: { budget: 30 },
    production: { ideas: 3, stress: 1 },
    description: "Des idées incroyables, mais 47 onglets ouverts dans la tête.",
    tags: ["creative", "ideas", "stress"],
    connectionsMax: 3,
    imageEmoji: "✏️",
  },
  {
    id: "senior-dev",
    name: "Développeuse senior",
    type: "person",
    rarity: "rare",
    level: 1,
    maxLevel: 3,
    cost: { budget: 60, ideas: 10 },
    production: { ideas: 4, reputation: 1 },
    description: "Transforme les prototypes bancals en vraies solutions.",
    tags: ["technical", "senior", "prototype"],
    connectionsMax: 4,
    imageEmoji: "👩‍💻",
  },
  {
    id: "kind-hr",
    name: "RH bienveillante",
    type: "person",
    rarity: "rare",
    level: 1,
    maxLevel: 3,
    cost: { budget: 45 },
    production: { happiness: 3, stress: -2 },
    description: "Repère les tensions avant qu’elles ne deviennent des réunions obligatoires.",
    tags: ["happiness", "support"],
    connectionsMax: 3,
    imageEmoji: "💚",
  },
  {
    id: "sales-enthusiast",
    name: "Commercial enthousiaste",
    type: "person",
    rarity: "rare",
    level: 1,
    maxLevel: 3,
    cost: { budget: 40 },
    production: { budget: 4, reputation: 1 },
    description: "Il vend même les post-its comme une innovation majeure.",
    tags: ["business", "budget"],
    connectionsMax: 3,
    imageEmoji: "📣",
  },
];

export const OBJECT_CARDS: GameCard[] = [
  {
    id: "post-it",
    name: "Post-it",
    type: "object",
    rarity: "common",
    level: 1,
    cost: { ideas: 1 },
    instantEffect: { postIts: 1 },
    description: "Petite idée qui colle partout. Sert aux connexions et combos.",
    tags: ["connector", "craft"],
    imageEmoji: "🗒️",
  },
  {
    id: "boss-mug",
    name: "Mug Boss Fuel",
    type: "object",
    rarity: "common",
    level: 1,
    cost: { budget: 5 },
    instantEffect: { energy: 3 },
    description: "+3 énergie immédiate. Très sérieux.",
    tags: ["energy", "comfort"],
    imageEmoji: "☕",
  },
  {
    id: "green-plant",
    name: "Plante verte",
    type: "object",
    rarity: "common",
    level: 1,
    cost: { budget: 8 },
    production: { happiness: 1, stress: -1 },
    description: "Apporte un peu de calme dans le chaos.",
    tags: ["comfort", "decor"],
    imageEmoji: "🪴",
  },
  {
    id: "cable",
    name: "Câble",
    type: "object",
    rarity: "common",
    level: 1,
    cost: { budget: 5 },
    description: "Permet de créer une connexion supplémentaire.",
    tags: ["connector", "technical"],
    imageEmoji: "🔌",
  },
  {
    id: "whiteboard",
    name: "Tableau blanc",
    type: "object",
    rarity: "uncommon",
    level: 1,
    cost: { budget: 20 },
    production: { ideas: 2 },
    description: "Double presque l’impression d’être organisé.",
    tags: ["ideas", "meeting"],
    imageEmoji: "⬜",
  },
  {
    id: "comfortable-chair",
    name: "Fauteuil confortable",
    type: "object",
    rarity: "uncommon",
    level: 1,
    cost: { budget: 20 },
    production: { happiness: 2, stress: -1 },
    description: "Un bon fauteuil peut sauver une journée.",
    tags: ["comfort"],
    imageEmoji: "💺",
  },
];

export const ACTION_CARDS: GameCard[] = [
  {
    id: "brainstorm-express",
    name: "Brainstorm express",
    type: "action",
    rarity: "common",
    level: 1,
    cost: { energy: 2 },
    instantEffect: { ideas: 6, stress: 1 },
    description: "Génère beaucoup d’idées, mais fatigue un peu l’équipe.",
    tags: ["ideas", "instant"],
    imageEmoji: "💡",
  },
  {
    id: "coffee-break",
    name: "Pause café générale",
    type: "action",
    rarity: "common",
    level: 1,
    cost: { budget: 5 },
    instantEffect: { energy: 8, happiness: 3 },
    description: "Tout le monde respire. Enfin presque.",
    tags: ["energy", "happiness"],
    imageEmoji: "☕",
  },
  {
    id: "effective-meeting",
    name: "Réunion efficace",
    type: "action",
    rarity: "uncommon",
    level: 1,
    cost: { energy: 3 },
    instantEffect: { ideas: 8, happiness: 1 },
    description: "Une réunion qui sert vraiment à quelque chose.",
    tags: ["meeting", "ideas"],
    imageEmoji: "🧠",
  },
  {
    id: "quick-training",
    name: "Formation rapide",
    type: "action",
    rarity: "uncommon",
    level: 1,
    cost: { budget: 15 },
    instantEffect: { ideas: 3, reputation: 1 },
    description: "Fait progresser l’équipe et débloque de nouvelles possibilités.",
    tags: ["training", "progression"],
    imageEmoji: "🎓",
  },
  {
    id: "team-building",
    name: "Team building",
    type: "action",
    rarity: "rare",
    level: 1,
    cost: { budget: 25 },
    instantEffect: { happiness: 15, stress: -5 },
    description: "Un moment gênant, mais étonnamment utile.",
    tags: ["happiness", "stress"],
    imageEmoji: "🎉",
  },
  {
    id: "all-nighter",
    name: "Nuit blanche",
    type: "action",
    rarity: "rare",
    level: 1,
    cost: { energy: 8, happiness: 5 },
    instantEffect: { ideas: 15, reputation: 3, stress: 8 },
    description: "Ça avance fort, mais à quel prix ?",
    tags: ["risk", "ideas", "stress"],
    imageEmoji: "🌙",
  },
];

export const PROJECT_CARDS: GameCard[] = [
  {
    id: "wobbly-prototype",
    name: "Prototype bancal",
    type: "project",
    rarity: "common",
    level: 1,
    cost: { ideas: 10, energy: 5, budget: 20 },
    instantEffect: { reputation: 15 },
    description: "Il tient avec du câble et de l’espoir.",
    tags: ["prototype", "project"],
    imageEmoji: "🤖",
  },
  {
    id: "landing-page",
    name: "Landing page express",
    type: "project",
    rarity: "uncommon",
    level: 1,
    cost: { ideas: 15, energy: 8, budget: 35 },
    instantEffect: { reputation: 25, budget: 20 },
    description: "Une belle page, trois boutons, et beaucoup d’ambition.",
    tags: ["business", "project"],
    imageEmoji: "🌐",
  },
  {
    id: "internal-app",
    name: "App interne",
    type: "project",
    rarity: "rare",
    level: 1,
    cost: { ideas: 30, energy: 15, budget: 70 },
    instantEffect: { reputation: 50, budget: 40 },
    description: "Personne ne sait vraiment qui l’a demandée, mais elle marche.",
    tags: ["technical", "project"],
    imageEmoji: "📱",
  },
  {
    id: "saas-product",
    name: "Produit SaaS",
    type: "project",
    rarity: "epic",
    level: 1,
    cost: { ideas: 60, energy: 25, budget: 150 },
    instantEffect: { reputation: 120, budget: 100 },
    description: "Abonnement mensuel, dashboard et rêves de scalabilité.",
    tags: ["business", "technical", "project"],
    imageEmoji: "☁️",
  },
  {
    id: "final-project",
    name: "Grand Projet final",
    type: "project",
    rarity: "legendary",
    level: 1,
    cost: { ideas: 100, energy: 40, budget: 250, reputation: 100 },
    instantEffect: { reputation: 300 },
    description: "Le projet qui transforme ton bureau en légende.",
    tags: ["final", "victory"],
    imageEmoji: "🏆",
  },
];

export const EVENT_CARDS: GameCard[] = [
  {
    id: "printer-breakdown",
    name: "Panne d’imprimante",
    type: "event",
    rarity: "common",
    level: 1,
    instantEffect: { energy: -3, stress: 3 },
    description: "Personne ne sait pourquoi, mais tout le monde est impacté.",
    tags: ["negative", "technical"],
    imageEmoji: "🖨️",
  },
  {
    id: "client-visit",
    name: "Visite client",
    type: "event",
    rarity: "uncommon",
    level: 1,
    instantEffect: { reputation: 8, budget: 10 },
    description: "Souriez, rangez les mugs, faites comme si tout était prévu.",
    tags: ["positive", "business"],
    imageEmoji: "🤝",
  },
  {
    id: "sudden-inspiration",
    name: "Inspiration soudaine",
    type: "event",
    rarity: "common",
    level: 1,
    instantEffect: { ideas: 10 },
    description: "Une idée arrive au moment où personne ne l’attendait.",
    tags: ["positive", "ideas"],
    imageEmoji: "✨",
  },
  {
    id: "demo-bug",
    name: "Bug de démo",
    type: "event",
    rarity: "uncommon",
    level: 1,
    instantEffect: { reputation: -5, stress: 5 },
    description: "Évidemment, ça marchait très bien hier.",
    tags: ["negative", "technical"],
    imageEmoji: "🐞",
  },
  {
    id: "surprise-deadline",
    name: "Deadline surprise",
    type: "event",
    rarity: "rare",
    level: 1,
    instantEffect: { energy: -5, stress: 8, ideas: 5 },
    description: "Il fallait le livrer hier. Apparemment.",
    tags: ["negative", "deadline"],
    imageEmoji: "⏰",
  },
  {
    id: "free-coffee",
    name: "Café offert",
    type: "event",
    rarity: "common",
    level: 1,
    instantEffect: { energy: 6, happiness: 2 },
    description: "Petite victoire collective.",
    tags: ["positive", "energy"],
    imageEmoji: "☕",
  },
];

export const ALL_CARDS = [
  ...BUILDING_CARDS,
  ...PERSON_CARDS,
  ...OBJECT_CARDS,
  ...ACTION_CARDS,
  ...PROJECT_CARDS,
  ...EVENT_CARDS,
];

export const STARTER_DECK_IDS = [
  "motivated-intern",
  "post-it",
  "post-it",
  "boss-mug",
  "green-plant",
  "brainstorm-express",
  "coffee-break",
  "open-space",
  "project-room",
  "wobbly-prototype",
];

export function getCardById(cardId: string): GameCard {
  const card = ALL_CARDS.find((candidate) => candidate.id === cardId);

  if (!card) {
    throw new Error(`Carte inconnue: ${cardId}`);
  }

  return card;
}
