export const GAME_ASSET_PATHS = {
  "worker-intern": "/game-assets/worker-intern.png",
  "worker-tired-dev": "/game-assets/worker-tired-dev.png",
  "worker-designer": "/game-assets/worker-designer.png",
  "worker-manager": "/game-assets/worker-manager.png",
  "worker-senior-dev": "/game-assets/worker-senior-dev.png",
  "worker-sales": "/game-assets/worker-sales.png",
  "worker-hr": "/game-assets/worker-hr.png",
  "worker-office-manager": "/game-assets/worker-office-manager.png",
  "worker-ai-agent": "/game-assets/worker-ai-agent.png",
  "location-starting-office": "/game-assets/location-starting-office.png",
  "location-coffee-machine": "/game-assets/location-coffee-machine.png",
  "location-open-space": "/game-assets/location-open-space.png",
  "location-project-room": "/game-assets/location-project-room.png",
  "location-relax-corner": "/game-assets/location-relax-corner.png",
  "location-meeting-room": "/game-assets/location-meeting-room.png",
  "location-creative-studio": "/game-assets/location-creative-studio.png",
  "location-client-desk": "/game-assets/location-client-desk.png",
  "location-autonomous-office": "/game-assets/location-autonomous-office.png",
  "resource-ideas": "/game-assets/resource-ideas.png",
  "resource-budget": "/game-assets/resource-budget.png",
  "resource-reputation": "/game-assets/resource-reputation.png",
  "resource-ambiance": "/game-assets/resource-ambiance.png",
  "resource-chaos": "/game-assets/resource-chaos.png",
  "resource-talent": "/game-assets/resource-talent.png",
  "icon-plus": "/game-assets/icon-plus.png",
  "icon-percent": "/game-assets/icon-percent.png",
  "icon-per-second": "/game-assets/icon-per-second.png",
  "icon-euro": "/game-assets/icon-euro.png",
  "icon-sparkle": "/game-assets/icon-sparkle.png",
  "badge-medal": "/game-assets/badge-medal.png",
  "badge-trophy": "/game-assets/badge-trophy.png",
  "badge-starburst": "/game-assets/badge-starburst.png",
  "badge-confetti": "/game-assets/badge-confetti.png",
  "badge-ribbon": "/game-assets/badge-ribbon.png",
  "badge-gem": "/game-assets/badge-gem.png",
  "badge-glow": "/game-assets/badge-glow.png",
  "badge-sparkles": "/game-assets/badge-sparkles.png",
  "ui-lock": "/game-assets/ui-lock.png",
  "ui-check": "/game-assets/ui-check.png",
  "ui-max": "/game-assets/ui-max.png",
  "ui-upgrade": "/game-assets/ui-upgrade.png",
  "ui-combo": "/game-assets/ui-combo.png",
  "ui-not-enough": "/game-assets/ui-not-enough.png",
} as const;

export type GameAssetId = keyof typeof GAME_ASSET_PATHS;

export function getGameAssetPath(assetId: GameAssetId): string {
  return GAME_ASSET_PATHS[assetId];
}
