import type {
  Incident,
  ManualAction,
  Milestone,
  OfficeLocation,
  Resources,
  Skill,
  Synergy,
  Worker,
} from "@/types/incremental";

export const STARTING_RESOURCES: Resources = {
  ideas: 0,
  budget: 50,
  ambiance: 50,
  reputation: 0,
  chaos: 0,
};

export const WORKERS: Worker[] = [
  {
    id: "intern",
    name: "Stagiaire motivé",
    description: "Il ne sait pas encore tout faire, mais il clique avec une confiance de comité de pilotage.",
    baseCost: 10,
    count: 0,
    level: 1,
    baseProduction: { ideas: 1 },
    unlockReputation: 0,
    emoji: "🧢",
    tags: ["junior", "ideas"],
  },
  {
    id: "tired-dev",
    name: "Développeur fatigué",
    description: "Produit des idées entre deux cafés et trois regards vides sur Jira.",
    baseCost: 45,
    count: 0,
    level: 1,
    baseProduction: { ideas: 5 },
    unlockReputation: 40,
    emoji: "💻",
    tags: ["technical", "ideas"],
  },
  {
    id: "designer",
    name: "Designer débordé",
    description: "Sort des idées brillantes et un débat de DA avant même le café.",
    baseCost: 90,
    count: 0,
    level: 1,
    baseProduction: { ideas: 8, chaos: 0.02 },
    unlockReputation: 120,
    emoji: "🎨",
    tags: ["creative", "ideas", "chaos"],
  },
  {
    id: "manager",
    name: "Manager inspirant",
    description: "Transforme le chaos en plan d’action, puis propose un point rapide.",
    baseCost: 160,
    count: 0,
    level: 1,
    baseProduction: { ambiance: 0.05, reputation: 0.1 },
    unlockReputation: 250,
    emoji: "🙋",
    tags: ["management", "ambiance"],
  },
  {
    id: "senior-dev",
    name: "Développeuse senior",
    description: "Répare les prototypes bancals pendant que tout le monde dit “ça marchait hier”.",
    baseCost: 260,
    count: 0,
    level: 1,
    baseProduction: { ideas: 25, reputation: 0.5 },
    unlockReputation: 500,
    emoji: "👩‍💻",
    tags: ["technical", "senior"],
  },
  {
    id: "sales",
    name: "Commercial enthousiaste",
    description: "Vend ce qui existe, ce qui arrive, et parfois ce qui vient de lui traverser l’esprit.",
    baseCost: 400,
    count: 0,
    level: 1,
    baseProduction: { budget: 5, reputation: 0.5, chaos: 0.01 },
    unlockReputation: 900,
    emoji: "📣",
    tags: ["business", "budget", "chaos"],
  },
  {
    id: "hr",
    name: "RH bienveillante",
    description: "Éteint les débuts d’incendie Slack avec des phrases très calmes.",
    baseCost: 650,
    count: 0,
    level: 1,
    baseProduction: { ambiance: 0.1, chaos: -0.03 },
    unlockReputation: 1500,
    emoji: "💚",
    tags: ["ambiance", "support"],
  },
  {
    id: "office-manager",
    name: "Office Manager",
    description: "Répare, range, organise, et sauve la boîte sans jamais faire de slide.",
    baseCost: 900,
    count: 0,
    level: 1,
    baseProduction: { budget: 8, chaos: -0.05 },
    unlockReputation: 2500,
    emoji: "🗂️",
    tags: ["support", "budget"],
  },
  {
    id: "ai-agent",
    name: "Agent IA",
    description: "Automatise tout, y compris les mauvaises idées qui avaient juste besoin de dormir.",
    baseCost: 3500,
    count: 0,
    level: 1,
    baseProduction: { ideas: 100, budget: 25, reputation: 2, chaos: 0.05 },
    unlockReputation: 6000,
    emoji: "🤖",
    tags: ["ai", "automation", "chaos"],
  },
];

export const LOCATIONS: OfficeLocation[] = [
  {
    id: "starting-office",
    name: "Bureau de départ",
    description: "Une table, deux chaises, et assez d’espoir pour ignorer le bail.",
    baseCost: 0,
    owned: true,
    level: 1,
    maxLevel: 1,
    effect: { ideasMultiplier: 0.05 },
    unlockReputation: 0,
    emoji: "🖥️",
    tags: ["starter"],
  },
  {
    id: "coffee-machine",
    name: "Machine à café",
    description: "Le vrai serveur central. Sans elle, même les idées demandent un arrêt maladie.",
    baseCost: 40,
    owned: false,
    level: 1,
    maxLevel: 5,
    effect: { ambianceBonus: 5, ideasMultiplier: 0.15 },
    unlockReputation: 20,
    emoji: "☕",
    tags: ["comfort", "energy"],
  },
  {
    id: "open-space",
    name: "Open Space",
    description: "Plus d’idées, plus de bruit, et zéro chance de finir une phrase.",
    baseCost: 90,
    owned: false,
    level: 1,
    maxLevel: 5,
    effect: { ideasMultiplier: 0.25, chaosPerSecond: 0.01 },
    unlockReputation: 60,
    emoji: "🏢",
    tags: ["ideas", "office"],
  },
  {
    id: "project-room",
    name: "Salle projet",
    description: "L’endroit où les idées mettent une chemise et prétendent être un plan.",
    baseCost: 180,
    owned: false,
    level: 1,
    maxLevel: 5,
    effect: { ideasMultiplier: 0.3, reputationMultiplier: 0.15 },
    unlockReputation: 120,
    emoji: "📋",
    tags: ["project", "ideas"],
  },
  {
    id: "relax-corner",
    name: "Coin détente",
    description: "Un canapé, deux plantes, et soudain le process semble moins dangereux.",
    baseCost: 300,
    owned: false,
    level: 1,
    maxLevel: 5,
    effect: { ambianceBonus: 10, chaosReduction: 0.03 },
    unlockReputation: 250,
    emoji: "🛋️",
    tags: ["comfort", "ambiance"],
  },
  {
    id: "meeting-room",
    name: "Salle réunion",
    description: "Zone à risque : une réunion utile peut arriver, mais rien n’est garanti.",
    baseCost: 450,
    owned: false,
    level: 1,
    maxLevel: 5,
    effect: { globalMultiplier: 0.2, chaosPerSecond: 0.015 },
    unlockReputation: 500,
    emoji: "🪑",
    tags: ["meeting", "global"],
  },
  {
    id: "creative-studio",
    name: "Studio créatif",
    description: "Des couleurs, des idées, et beaucoup trop de versions “final_final_v3”.",
    baseCost: 700,
    owned: false,
    level: 1,
    maxLevel: 5,
    effect: { ideasMultiplier: 0.5, chaosPerSecond: 0.02 },
    unlockReputation: 900,
    emoji: "🎨",
    tags: ["creative", "ideas"],
  },
  {
    id: "client-desk",
    name: "Accueil client",
    description: "Pour sourire fort et cacher que le dossier partagé est introuvable.",
    baseCost: 1200,
    owned: false,
    level: 1,
    maxLevel: 5,
    effect: { reputationMultiplier: 0.4, budgetMultiplier: 0.15 },
    unlockReputation: 1500,
    emoji: "🤝",
    tags: ["business", "reputation"],
  },
  {
    id: "autonomous-office",
    name: "Bureau autonome",
    description: "Le bureau tourne presque seul. Quelqu’un surveille quand même la machine à café.",
    baseCost: 15000,
    owned: false,
    level: 1,
    maxLevel: 5,
    effect: { globalMultiplier: 1, chaosReduction: 0.05 },
    unlockReputation: 25000,
    emoji: "🏆",
    tags: ["final", "automation"],
  },
];

export const SYNERGIES: Synergy[] = [
  {
    id: "caffeinated-dev",
    name: "Développeur caféiné",
    description: "Machine à café + développeur : les idées partent en sprint sans demander l’avis du planning.",
    requirements: { workers: { "tired-dev": 1 }, locations: ["coffee-machine"] },
    effect: { ideasMultiplier: 0.25 },
    discovered: false,
    emoji: "☕",
  },
  {
    id: "junior-team",
    name: "Équipe junior",
    description: "Cinq stagiaires motivés dans la même direction. Enfin, globalement.",
    requirements: { workers: { intern: 5 }, locations: ["open-space"] },
    effect: { ideasMultiplier: 0.2 },
    discovered: false,
    emoji: "🧢",
  },
  {
    id: "permanent-brainstorm",
    name: "Brainstorm permanent",
    description: "La salle projet transforme le chaos créatif en mur de post-its presque lisible.",
    requirements: { workers: { designer: 1 }, locations: ["project-room"] },
    effect: { ideasMultiplier: 0.3 },
    discovered: false,
    emoji: "💡",
  },
  {
    id: "calm-team",
    name: "Équipe sereine",
    description: "RH bienveillante + coin détente : l’ambiance reçoit enfin un badge d’accès.",
    requirements: { workers: { hr: 1 }, locations: ["relax-corner"] },
    effect: { ambianceBonus: 10, chaosReduction: 0.05 },
    discovered: false,
    emoji: "💚",
  },
  {
    id: "business-pipeline",
    name: "Pipeline business",
    description:
      "Un commercial avec un accueil client peut transformer une idée floue en facture pressée.",
    requirements: { workers: { sales: 1 }, locations: ["client-desk"] },
    effect: { budgetMultiplier: 0.5, reputationMultiplier: 0.2 },
    discovered: false,
    emoji: "📣",
  },
  {
    id: "office-autopilot",
    name: "Office Autopilot",
    description: "L’Agent IA et le Bureau autonome font tourner le village pendant que le comité cherche le lien Teams.",
    requirements: { workers: { "ai-agent": 1 }, locations: ["autonomous-office"] },
    effect: { globalMultiplier: 1, chaosReduction: 0.1 },
    discovered: false,
    emoji: "🤖",
  },
];

export const INCIDENTS: Incident[] = [
  {
    id: "coffee-noise",
    title: "Machine à café suspecte",
    description:
      "La machine à café tousse comme un vieux serveur. Tout l’open-space nie le problème.",
    emoji: "☕",
    choices: [
      { id: "repair", label: "La réparer proprement", effect: { budget: -100, ambiance: 10, chaos: -5 } },
      {
        id: "hit",
        label: "Taper dessus doucement",
        effect: {},
        chance: {
          successRate: 0.5,
          successEffect: { ambiance: 5, budget: 20 },
          failEffect: { ambiance: -10, chaos: 10 },
        },
      },
      { id: "ignore", label: "Dire que c’est normal", effect: { budget: 20, ambiance: -5, chaos: 5 } },
    ],
  },
  {
    id: "wild-meeting",
    title: "Réunion sauvage",
    description: "Un manager vient de prononcer “point rapide” avec une invitation de 2h.",
    emoji: "🪑",
    choices: [
      { id: "accept", label: "Accepter", effect: { ideas: 20, ambiance: -10, chaos: 5 } },
      {
        id: "standup",
        label: "Transformer en stand-up 10 min",
        effect: { ideas: 10, ambiance: 5, reputation: 5 },
      },
      { id: "email", label: "Envoyer un mail à la place", effect: { budget: 5, ambiance: 3, chaos: -3 } },
    ],
  },
  {
    id: "intern-blockchain",
    title: "Grande idée du stagiaire",
    description: "Le stagiaire propose de refaire tout le produit en blockchain. Le tableau blanc tremble.",
    emoji: "🧢",
    choices: [
      { id: "listen", label: "L’écouter vraiment", effect: { ideas: 30, ambiance: 5, chaos: 5 } },
      { id: "v2", label: "Dire ‘on garde ça pour V2’", effect: { ideas: 10, budget: 10 } },
      { id: "whiteboard", label: "Lui confier le tableau blanc", effect: { ideas: 20, reputation: 10, chaos: 10 } },
    ],
  },
  {
    id: "microwave-fish",
    title: "Poisson au micro-ondes",
    description: "Quelqu’un a réchauffé du poisson à 9h12. La QVT demande un plan d’urgence.",
    emoji: "🐟",
    choices: [
      { id: "windows", label: "Ouvrir les fenêtres", effect: { budget: -5, ambiance: 5, chaos: -5 } },
      { id: "rule", label: "Installer une règle officielle", effect: { reputation: 5, ambiance: -3, chaos: -2 } },
      { id: "printer", label: "Accuser l’imprimante", effect: { chaos: 10, ideas: 10 } },
    ],
  },
  {
    id: "postit-wall",
    title: "Mur de post-its illisible",
    description: "Le mur est couvert de post-its. Même les post-its ne savent plus qui décide.",
    emoji: "🗒️",
    choices: [
      { id: "colors", label: "Ranger par couleur", effect: { ideas: -20, ambiance: 10, chaos: -10 } },
      { id: "keep-all", label: "Tout garder", effect: { ideas: 30, ambiance: -10, chaos: 10 } },
      { id: "photo", label: "Faire une photo et fuir", effect: { reputation: 5, chaos: 5 } },
    ],
  },
  {
    id: "designer-redesign",
    title: "Refonte de DA imprévue",
    description:
      "Le designer veut refaire le logo, les couleurs, et probablement la personnalité de la cafetière.",
    emoji: "🎨",
    choices: [
      { id: "give-time", label: "Lui donner 30 minutes", effect: { ideas: 50, budget: -5, chaos: 5 } },
      { id: "keep-simple", label: "Dire ‘on garde simple’", effect: { budget: 20, ambiance: -5, chaos: -5 } },
      {
        id: "design-sprint",
        label: "Organiser un mini design sprint",
        effect: { ideas: 30, reputation: 10, ambiance: 5 },
      },
    ],
  },
  {
    id: "sales-fake-feature",
    title: "Feature inexistante vendue",
    description: "Le commercial a promis un dashboard IA vocal en 3D pour lundi. Le lundi n’a pas été consulté.",
    emoji: "📣",
    choices: [
      { id: "pretend", label: "Faire semblant que c’était prévu", effect: { budget: 50, reputation: 10, chaos: 15 } },
      { id: "reframe", label: "Recadrer gentiment", effect: { ambiance: 5, budget: -10, chaos: -10 } },
      { id: "prototype", label: "Lancer un prototype express", effect: { ideas: -20, reputation: 25, chaos: 10 } },
    ],
  },
  {
    id: "demo-bug",
    title: "Bug de démo",
    description: "Évidemment, ça marchait hier. Phrase officielle, valeur juridique zéro.",
    emoji: "🐞",
    choices: [
      { id: "fix-live", label: "Corriger en live", effect: { ideas: -20, reputation: 10, chaos: 5 } },
      { id: "call-it-beta", label: "Dire que c’est une bêta", effect: { reputation: -5, chaos: -5 } },
      { id: "blame-cache", label: "Accuser le cache navigateur", effect: { ambiance: 3, chaos: 3 } },
    ],
  },
  {
    id: "slack-fire",
    title: "Slack en feu",
    description: "Quelqu’un a lancé un débat dans #general. Les gifs arrivent, la productivité part.",
    emoji: "🔥",
    minChaos: 30,
    choices: [
      { id: "mute", label: "Mute le canal 1h", effect: { ambiance: 5, chaos: -10 } },
      { id: "thread", label: "Demander de passer en thread", effect: { reputation: 5, chaos: -5 } },
      { id: "react-gif", label: "Répondre avec un GIF", effect: { ambiance: 10, chaos: 10 } },
    ],
  },
  {
    id: "ai-too-motivated",
    title: "Agent IA trop motivé",
    description: "L’Agent IA veut remplacer toutes les réunions par des poèmes. Le comité hésite sérieusement.",
    emoji: "🤖",
    minChaos: 50,
    choices: [
      { id: "accept", label: "Accepter", effect: { ideas: 100, chaos: 20 } },
      { id: "refuse", label: "Refuser poliment", effect: { ambiance: 5, chaos: -10 } },
      {
        id: "test-client",
        label: "Tester sur un client",
        effect: {},
        chance: {
          successRate: 0.5,
          successEffect: { reputation: 200, budget: 50 },
          failEffect: { reputation: -50, chaos: 30 },
        },
      },
    ],
  },
];

export const MANUAL_ACTIONS: ManualAction[] = [
  {
    id: "brainstorm",
    name: "Brainstorm",
    description: "+12 idées. Le tableau blanc accepte le choc.",
    cooldownMs: 3000,
    lastUsedAt: null,
    effect: { ideas: 12 },
    emoji: "💡",
  },
  {
    id: "coffee-break",
    name: "Pause café",
    description: "+5 ambiance. Le bureau respire par la cafetière.",
    cooldownMs: 15000,
    lastUsedAt: null,
    effect: { ambiance: 5 },
    emoji: "☕",
  },
  {
    id: "client-pitch",
    name: "Pitch client",
    description: "Transforme 25 idées en budget, réputation, et sourire commercial.",
    cooldownMs: 20000,
    lastUsedAt: null,
    cost: { ideas: 25 },
    effect: { budget: 30, reputation: 15 },
    emoji: "🤝",
  },
];

export const SKILLS: Skill[] = [
  {
    id: "organization",
    name: "Organisation",
    branch: "productivity",
    description: "+10 % idées. Les post-its arrêtent de vivre leur vie.",
    cost: 1,
    unlockReputation: 20,
    effect: { ideasMultiplier: 0.1 },
    unlocked: false,
    emoji: "📋",
  },
  {
    id: "efficient-meetings",
    name: "Réunions efficaces",
    branch: "productivity",
    description: "+20 % efficacité globale. Oui, une réunion peut servir.",
    cost: 1,
    unlockReputation: 120,
    effect: { globalMultiplier: 0.2 },
    unlocked: false,
    emoji: "🧠",
  },
  {
    id: "postit-empire",
    name: "Empire du Post-it",
    branch: "productivity",
    description: "+50 % idées. Le mur devient officiellement incontrôlable.",
    cost: 2,
    unlockReputation: 500,
    effect: { ideasMultiplier: 0.5 },
    unlocked: false,
    emoji: "🗒️",
  },
  {
    id: "green-plants",
    name: "Plantes vertes",
    branch: "comfort",
    description: "+5 ambiance. Les plantes jugent moins que le comité.",
    cost: 1,
    unlockReputation: 60,
    effect: { ambianceBonus: 5 },
    unlocked: false,
    emoji: "🪴",
  },
  {
    id: "coffee-culture",
    name: "Culture café",
    branch: "comfort",
    description: "+10 ambiance. Le carburant social passe en illimité.",
    cost: 1,
    unlockReputation: 250,
    effect: { ambianceBonus: 10 },
    unlocked: false,
    emoji: "☕",
  },
  {
    id: "team-culture",
    name: "Culture d’équipe",
    branch: "comfort",
    description: "Ambiance minimum 50. La mauvaise humeur signe une charte.",
    cost: 2,
    unlockReputation: 1500,
    effect: { minAmbiance: 50 },
    unlocked: false,
    emoji: "💚",
  },
  {
    id: "pitch-deck",
    name: "Pitch deck",
    branch: "business",
    description: "+10 % réputation. Les slides font semblant d’être modestes.",
    cost: 1,
    unlockReputation: 120,
    effect: { reputationMultiplier: 0.1 },
    unlocked: false,
    emoji: "📊",
  },
  {
    id: "clear-offer",
    name: "Offre claire",
    branch: "business",
    description: "+20 % budget. Même la finance comprend la phrase.",
    cost: 1,
    unlockReputation: 500,
    effect: { budgetMultiplier: 0.2 },
    unlocked: false,
    emoji: "💼",
  },
  {
    id: "scale-up",
    name: "Scale-up",
    branch: "business",
    description: "+50 % budget et réputation. Le reporting commence à transpirer.",
    cost: 3,
    unlockReputation: 6000,
    effect: { budgetMultiplier: 0.5, reputationMultiplier: 0.5 },
    unlocked: false,
    emoji: "🚀",
  },
];

export const MILESTONES: Milestone[] = [
  {
    id: "ten-interns",
    title: "Promo de stagiaires",
    description: "Recruter 10 stagiaires. Le bureau découvre la puissance du badge temporaire. Bonus global +10 %.",
    condition: { workerCount: { workerId: "intern", count: 10 } },
    reward: { globalMultiplier: 0.1 },
    achieved: false,
    emoji: "🧢",
  },
  {
    id: "first-office",
    title: "Vrai bureau",
    description: "Construire l’Open Space. Le bruit monte, les idées aussi. +10 % idées.",
    condition: { locationOwned: "open-space" },
    reward: { ideasMultiplier: 0.1 },
    achieved: false,
    emoji: "🏢",
  },
  {
    id: "happy-office",
    title: "Bonne ambiance",
    description: "Atteindre 90 ambiance. Même le calendrier paraît moins hostile. +10 % réputation.",
    condition: { ambiance: 90 },
    reward: { reputationMultiplier: 0.1 },
    achieved: false,
    emoji: "😊",
  },
  {
    id: "one-million-ideas",
    title: "Machine à idées",
    description: "Atteindre 1 000 000 idées cumulées. Le mur de post-its demande un syndicat. +20 % idées.",
    condition: { totalIdeas: 1_000_000 },
    reward: { ideasMultiplier: 0.2 },
    achieved: false,
    emoji: "💡",
  },
  {
    id: "synergy-master",
    title: "Bureau combo",
    description: "Découvrir 5 combos. Le bureau prétend que tout était prévu. +20 % global.",
    condition: { synergiesCount: 5 },
    reward: { globalMultiplier: 0.2 },
    achieved: false,
    emoji: "🔗",
  },
];
