import type { SkillNode } from "@/types/game";

export const SKILL_NODES: SkillNode[] = [
  {
    id: "productivity-organization",
    name: "Organisation",
    branch: "productivity",
    description: "+1 idée par tour.",
    cost: 1,
    prerequisites: [],
    effect: { resourceBonus: { ideas: 1 } },
    iconEmoji: "📋",
  },
  {
    id: "productivity-efficient-meetings",
    name: "Réunions efficaces",
    branch: "productivity",
    description: "Les salles de réunion ne génèrent plus de stress.",
    cost: 1,
    prerequisites: ["productivity-organization"],
    effect: {},
    iconEmoji: "🧠",
  },
  {
    id: "productivity-postit-empire",
    name: "Empire du Post-it",
    branch: "productivity",
    description: "Les connexions coûtent 0 post-it une fois sur deux.",
    cost: 2,
    prerequisites: ["productivity-efficient-meetings"],
    effect: { connectionDiscount: 0.5 },
    iconEmoji: "🗒️",
  },
  {
    id: "comfort-green-office",
    name: "Bureau végétal",
    branch: "comfort",
    description: "-1 stress par tour.",
    cost: 1,
    prerequisites: [],
    effect: { resourceBonus: { stress: -1 } },
    iconEmoji: "🪴",
  },
  {
    id: "comfort-couch-culture",
    name: "Culture canapé",
    branch: "comfort",
    description: "+2 bonheur par tour.",
    cost: 1,
    prerequisites: ["comfort-green-office"],
    effect: { resourceBonus: { happiness: 2 } },
    iconEmoji: "🛋️",
  },
  {
    id: "comfort-zen-office",
    name: "Bureau zen",
    branch: "comfort",
    description: "Le stress monte 25 % moins vite.",
    cost: 2,
    prerequisites: ["comfort-couch-culture"],
    effect: {},
    iconEmoji: "🧘",
  },
  {
    id: "technical-spreadsheet",
    name: "Tableur",
    branch: "technical",
    description: "+2 budget par tour.",
    cost: 1,
    prerequisites: [],
    effect: { resourceBonus: { budget: 2 } },
    iconEmoji: "📊",
  },
  {
    id: "technical-macro",
    name: "Macro",
    branch: "technical",
    description: "+1 action virtuelle par tour. Pour le MVP : pioche +1 carte.",
    cost: 1,
    prerequisites: ["technical-spreadsheet"],
    effect: {},
    iconEmoji: "⌨️",
  },
  {
    id: "technical-ai-agent",
    name: "Agent IA",
    branch: "technical",
    description: "Débloque une production automatique d’idées et de budget.",
    cost: 3,
    prerequisites: ["technical-macro"],
    effect: { resourceBonus: { ideas: 2, budget: 5 } },
    iconEmoji: "🤖",
  },
];
